{{- if .Values.disruption.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "service-platform.fullname" . }}
  labels:
    {{- include "service-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.disruption.minAvailable }}
  selector:
    matchLabels:
      {{- include "service-platform.selectorLabels" . | nindent 6 }}
{{- end }}
